const Input = (props) => {
  const array = [
    "Abbottabad",
    " Abdul Hakim",
    "Aberdeen",
    "Abilene",
    "Ahmadpur East",
    "Akron",
    "Albany",
    "Albuquerque",
    "Alexandria",
    "Aliabad",
    "Allentown",
    "Alpurai",
    "Amarillo",
    "Anaheim",
    "Anchorage",
    "Ann Arbor",
    "Antioch",
    "Appleton",
    "Apple Valley",
    "Arlington",
    "Arvada",
    "Asheville",
    "Athens",
    "Athmuqam",
    "Atlanta",
    "Atlantic City",
    " Attock City",
    "Attock Khurd",
    "Augusta",
    "Aurora",
    "Austin",
    "Awaran",
    "Badin",
    "Bagh",
    "Bahawalnagar",
    "Bahawalpur",
    "Bakersfield",
    "Baltimore",
    "Bannu",
    "Barkhan",
    "Barnstable",
    "Batgram",
    "Baton Rouge",
    "Beaumont",
    "Bel Air",
    "Bellevue",
    "Berkeley",
    "Bethlehem",
    "Bhakkar",
    "Bhalwal",
    "Billings",
    "Birmingham",
    "Bloomington",
    "Boise",
    "Boise City",
    "Bonita Springs",
    "Boston",
    "Boulder",
    "Bradenton",
    "Bremerton",
    "Bridgeport",
    "Brighton",
    "Brownsville",
    "Bryan",
    "Buffalo",
    "Burbank",
    "Burlington",
    "Cambridge",
    "Canton",
    "Cape Coral",
    "Carrollton",
    "Cary",
    "Cathedral City",
    "Cedar Rapids",
    "Chakwal",
    "Chaman",
    "Champaign",
    "Chandler",
    "Charleston",
    "Charlotte",
    "Charsadda",
    "Chattanooga",
    "Chenab Nagar",
    "Chesapeake",
    "Chicago",
    "Chilas",
    "Chiniot",
    "Chishtian",
    "Chitral",
    "Chula Vista",
    "Chunian",
    "Cincinnati",
    "Clarke County",
    "Clarksville",
    "Clearwater",
    "Cleveland",
    "College Station",
    "Colorado Springs",
    "Columbia",
    "Columbus",
    "Concord",
    "Coral Springs",
    "Corona",
    "Corpus Christi",
    "Costa Mesa",
    "Dadu",
    "Daggar",
    "Dainyor",
    "Dalbandin",
    "Dallas",
    "Daly City",
    "Danbury",
    "Dasu",
    "Davenport",
    "Davidson County",
    "Dayton",
    "Daytona Beach",
    "Deltona",
    "Denton",
    "Denver",
    "Dera Allahyar",
    "Dera Bugti",
    "Dera Ghazi Khan",
    "Dera Ismail Khan",
    "Dera Murad Jamali",
    "Des Moines",
    "Detroit",
    "Dipalpur",
    "Downey",
    "Duluth",
    "Durham",
    "Eidgah",
    "Elizabeth",
    "Elk Grove",
    "Elkhart",
    "El Monte",
    "El Paso",
    "Erie",
    "Escondido",
    "Eugene",
    "Evansville",
    "Fairfield",
    "Faisalabad",
    "Fargo",
    "Fayetteville",
    "Fitchburg",
    "Flint",
    "Fontana",
    "Fort Collins",
    "Fort Lauderdale",
    "Fort Smith",
    "Fort Walton Beach",
    "Fort Wayne",
    "Fort Worth",
    "Frederick",
    "Fremont",
    "Fresno",
    "Fullerton",
    "Gainesville",
    "Gakuch",
    "Gandava",
    "Garden Grove",
    "Garland",
    "Gastonia",
    "Ghotki",
    "Gilbert",
    "Gilgit",
    "Glendale",
    "Gojra",
    "Grand Prairie",
    "Grand Rapids",
    "Grayslake",
    "GreenBay",
    "Green Bay",
    "Greensboro",
    "Greenville",
    "Gujranwala",
    "Gujrat",
    "Gulfport-Biloxi",
    "Gwadar",
    "Hafizabad",
    "Hagerstown",
    "Hampton",
    "Hangu",
    "Haripur",
    "Harlingen",
    "Harrisburg",
    "Hartford",
    "Harunabad",
    "Hasilpur",
    "Hassan Abdal",
    "Havre de Grace",
    "Hayward",
    "Hemet",
    "Henderson",
    "Hesperia",
    "Hialeah",
    "Hickory",
    "High Point",
    "Hollywood",
    "Honolulu",
    "Houma",
    "Houston",
    "Howell",
    "Hujra Shah Muqim",
    "Huntington",
    "Huntington Beach",
    "Huntsville",
    "Hyderabad City",
    "Independence",
    "Indianapolis",
    "Inglewood",
    "Irvine",
    "Irving",
    "Islamabad",
    "Jackson",
    "Jacksonville",
    "Jacobabad",
    "Jalalpur Jattan",
    "Jamshoro",
    "Jaranwala",
    "Jefferson",
    "Jersey City",
    "Jhang",
    "Jhelum",
    "Johnson City",
    "Joliet",
    "Kabirwala",
    "Kahror Pakka",
    "Kailua",
    "Kalamazoo",
    "Kalat",
    "Kamalia",
    "Kandhkot",
    "Kaneohe",
    "Kansas City",
    "Karachi",
    "Karachi",
    "Karak",
    "Kasur",
    "Kennewick",
    "Kenosha",
    "Khairpur Mir’s",
    "Khanewal",
    "Khanpur",
    "Kharan",
    "Kharian",
    "Khushab",
    "Khuzdar",
    "Khuzdar",
    "Killeen",
    "Kissimmee",
    "Knoxville",
    "Kohat",
    "Kohlu",
    " Kot Addu",
    "Kotli",
    "Kulachi",
    "Kundian",
    "Lacey",
    "Lafayette",
    "Lahore",
    "Lake Charles",
    "Lakeland",
    "Lakewood",
    "Lakki",
    "Lala Musa",
    "Lancaster",
    "Lansing",
    "Laredo",
    "Larkana",
    "Las Cruces",
    "Las Vegas",
    "Layton",
    "Leiah",
    "Leominster",
    "Lewisville",
    "Lexington",
    "Lincoln",
    "Little Rock",
    "Lodhran",
    "Long Beach",
    "Lorain",
    "Loralai",
    "Los Angeles",
    "Louisville",
    "Lowell",
    "Lubbock",
    "Macon",
    "Madison",
    "Malakand",
    "Manchester",
    "Mandi Bahauddin",
    "Mandi Burewala",
    "Mansehra",
    "Mardan",
    "Marina",
    "Marysville",
    "Mastung",
    "Matiari",
    "McAllen",
    "McHenry",
    "Medford",
    "Melbourne",
    "Memphis",
    "Merced",
    "Mesa",
    "Mesquite",
    "Miami",
    "Mian Channun",
    "Mianwali",
    "Milwaukee",
    "Mingaora",
    "Minneapolis",
    "Miramar",
    "Mirpur Khas",
    "Mission Viejo",
    "Mobile",
    "Modesto",
    "Monroe",
    "Monterey",
    "Montgomery",
    "Moreno Valley",
    "Multan",
    "Murfreesboro",
    "Muridke",
    "Murrieta",
    "Musa Khel Bazar",
    "Muskegon",
    "Muzaffarabad",
    "Muzaffargarh",
    "Myrtle Beach",
    "Nankana Sahib",
    "Naperville",
    "Naples",
    "Narowal",
    "Nashua",
    "Nashville",
    "Naushahro Firoz",
    "Nawabshah",
    "Newark",
    "New Bedford",
    "Newburgh",
    "New Haven",
    "New London",
    "New Mirpur",
    "New Orleans",
    "Newport News",
    "New York",
    "New York City",
    "Norfolk",
    "Normal",
    "Norman",
    "North Charleston",
    "North Las Vegas",
    "North Port",
    "Norwalk",
    "Norwich",
    "Nowshera",
    "Oakland",
    "Ocala",
    "Oceanside",
    "Odessa",
    "Ogden",
    "Okara",
    "Oklahoma City",
    "Olathe",
    "Olympia",
    "Omaha",
    "Ontario",
    "Orange",
    "Orem",
    "Orlando",
    "Overland Park",
    "Oxnard",
    "Pakpattan",
    "Palm Bay",
    "Palmdale",
    "Palm Springs",
    "Panama City",
    "Panjgur",
    "Parachinar",
    "Pasadena",
    "Pasrur",
    "Paterson",
    "Pattoki",
    "Pembroke Pines",
    "Pensacola",
    "Peoria",
    "Peshawar",
    "Philadelphia",
    "Phoenix",
    "Pishin",
    "Pittsburgh",
    "Plano",
    "Pomona",
    "Pompano Beach",
    "Port Arthur",
    "Portland",
    "Port Orange",
    "Port Saint Lucie",
    "Portsmouth",
    "Port St. Lucie",
    "Poughkeepsie",
    "Providence",
    "Provo",
    "Pueblo",
    "Punta Gorda",
    "Qila Saifullah",
    "Quetta",
    "Racine",
    "Rahimyar Khan",
    "Rajanpur",
    "Raleigh",
    "Rancho Cucamonga",
    "Rawala Kot",
    "Rawalpindi",
    "Reading",
    "Redding",
    "Reno",
    "Richland",
    "Richmond",
    "Richmond County",
    "Risalpur Cantonment",
    "Riverside",
    "Roanoke",
    "Rochester",
    "Rockford",
    "Roseville",
    "Round Lake Beach",
    "Sacramento",
    "Saddiqabad",
    "Saginaw",
    "Sahiwal",
    "Saidu Sharif",
    "Saint Louis",
    "Saint Paul",
    "Saint Petersburg",
    "Salem",
    "Salinas",
    "Salt Lake City",
    "Sambrial",
    "Samundri",
    "San Antonio",
    "San Bernardino",
    "San Buenaventura",
    "San Diego",
    "San Francisco",
    "Sanghar",
    "San Jose",
    "Santa Ana",
    "Santa Barbara",
    "Santa Clara",
    "Santa Clarita",
    "Santa Cruz",
    "Santa Maria",
    "Santa Rosa",
    "Sarasota",
    "Sargodha",
    "Savannah",
    "Scottsdale",
    "Scranton",
    "Seaside",
    "Seattle",
    "Sebastian",
    "Shahdad Kot",
    "Shakargarh",
    "Shekhupura",
    "Shikarpur",
    "Shreveport",
    "Shujaabad",
    "Sialkot",
    "Sibi",
    "Simi Valley",
    "Sioux City",
    "Sioux Falls",
    "South Bend",
    "South Lyon",
    "Spartanburg",
    "Spokane",
    "Springdale",
    "Springfield",
    "St. Louis",
    "St. Paul",
    "St. Petersburg",
    "Stamford",
    "Sterling Heights",
    "Stockton",
    "Sukkur",
    "Sunnyvale",
    "Swabi",
    "Syracuse",
    "Tacoma",
    "Tallahassee",
    "Tampa",
    "Tando Allahyar",
    "Tando Muhammad Khan",
    "Tank",
    "Temecula",
    "Tempe",
    "Thatta",
    "Thornton",
    "Thousand Oaks",
    "Timargara",
    "Toba Tek Singh",
    "Toledo",
    "Topeka",
    "Torrance",
    "Trenton",
    "Tucson",
    "Tulsa",
    "Turbat",
    "Tuscaloosa",
    "Tyler",
    "Umarkot",
    "Upper Dir",
    "Uthal",
    "Utica",
    "Vallejo",
    "Vancouver",
    "Vero Beach",
    "Victorville",
    "Vihari",
    "Virginia Beach",
    "Visalia",
    "Waco",
    "Warren",
    "Washington",
    "Waterbury",
    "Waterloo",
    "West Covina",
    "Westminster",
    "West Valley City",
    "Wichita",
    "Wilmington",
    "Winston",
    "Winter Haven",
    "Worcester",
    "Yakima",
    "Yonkers",
    "York",
    "Youngstown",
    "Zhob",
    "Ziarat",
  ];

  return (
    <form className="form-control" onSubmit={props.getWeather}>
      <select id="cars" name="city">
        <option selected> {props.city} </option>
        {array.map((data, index) => (
          <option value={data} key={index}>
            {data}
          </option>
        ))}
      </select>

      <button className="btn">Search</button>
    </form>
  );
};

export default Input;
